//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Topee.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TopeeDatabaseEntities : DbContext
    {
        public TopeeDatabaseEntities()
            : base("name=TopeeDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Classify> Classify { get; set; }
        public virtual DbSet<favorite_goods> favorite_goods { get; set; }
        public virtual DbSet<favorite_store> favorite_store { get; set; }
        public virtual DbSet<Goods> Goods { get; set; }
        public virtual DbSet<hash_tag> hash_tag { get; set; }
        public virtual DbSet<shop_car> shop_car { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
